# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hamming <- function(x, y) {
    .Call(`_matchr_hamming`, x, y)
}

reduce_int <- function(x) {
    .Call(`_matchr_reduce_int`, x)
}

rgb_to_grey <- function(x) {
    .Call(`_matchr_rgb_to_grey`, x)
}

