# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

row_means <- function(x) {
    .Call(`_matchr_row_means`, x)
}

rm_bb_c <- function(x) {
    .Call(`_matchr_rm_bb_c`, x)
}

rm_bb_g <- function(x) {
    .Call(`_matchr_rm_bb_g`, x)
}

rm_bb_i_c <- function(x) {
    .Call(`_matchr_rm_bb_i_c`, x)
}

rm_bb_i_g <- function(x) {
    .Call(`_matchr_rm_bb_i_g`, x)
}

hamming <- function(x, y) {
    .Call(`_matchr_hamming`, x, y)
}

reduce_int <- function(x) {
    .Call(`_matchr_reduce_int`, x)
}

rgb_to_grey <- function(x) {
    .Call(`_matchr_rgb_to_grey`, x)
}

